name: Deploy to Targetboard Web Server (Password Auth)

on:
  push: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass openssh-client

      - name: Run remote deploy commands via SSH
        run: bash devops/scripts/deploy.sh

