name: Deploy to Targetboard Web Server (Password Auth)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass openssh-client git npm

      - name: Run remote deploy commands via SSH
        run: |
          sshpass -p "yu2iu9s00XWaMnf" ssh -o StrictHostKeyChecking=no root@159.65.158.178 << 'EOF'
            cd /root/targetboard-webs
            git pull
            npm install
            pm2 restart backend
          EOF
